version: '2.0'
services:
  send-files:
    build: docker/send-file
    privileged: true
    extra_hosts:
      - "nfs:35.205.41.176"
    volumes:
      - './docker/send-file/script.sh:/script.sh'
  get-files:
    build: docker/get-file
    privileged: true
    extra_hosts:
      - "nfs:35.205.41.176"
    volumes:
      - './docker/get-file/script.sh:/script.sh'

volumes:
  nfsshare:
